### ISSUE TITLE
Missing Professor: Dr. Choi

### ISSUE THREAD

**Issue by BurningEmbyr** [s1ag/Gerbot#29]
I'm currently taking Computer Logic and Organization with Dr. Jongouk Choi, a new professor who isn't even quite fully added by UCF yet. When attempting to register for the class, Gerbot did not recognize his name as a professor and told me to submit an issue here. Syllabus is attached.
[CDA3013_Fall_2022_Syllabus.docx](https://github.com/s1ag/Gerbot/files/9425981/CDA3013_Fall_2022_Syllabus.docx).

**Comment by zenith110** [comment]
Have added the professor to the list, thank you for creating this issue!
